### ISSUE TITLE
problems using tide-websockets and tide-sqlx together

### ISSUE THREAD

**Issue by chinatsu** [http-rs/tide-websockets#23]
hello!

i'm just starting a new project where i'd like to have a service that handles websockets and does some fiddling with a database, perhaps even at the same time. so i figured it would be a good idea to use tide-websockets and [tide-sqlx](https://github.com/eaze/tide-sqlx), since both projects are listed as middlewares in the [tide readme](https://github.com/http-rs/tide#middleware)!

unfortunately, using the tide-sqlx middleware with an endpoint that uses tide-websockets causes an error. my working theory is that tide-websockets does something funky with tide's request instance, but it's tide-sqlx that complains. i'm taking my chances and starting my issue here since you might know what's up.

consider these dependencies
```toml
[dependencies]
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
tide-sqlx = "0.6.1"
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls", "postgres" ] }
tide-websockets = "0.4.0"
dotenv = "0.15.0"
```

and this (simplified) program,
```rust
use tide::Request;
use async_std::prelude::*;
use sqlx::postgres::Postgres;
use tide_sqlx::SQLxMiddleware;
use dotenv::dotenv;
use std::env;
use tide_websockets::{Message, WebSocket, WebSocketConnection};


#[async_std::main]
async fn main() -> tide::Result<()> {
    dotenv().ok();

    let mut app = tide::new();
    app.with(SQLxMiddleware::<Postgres>::new(&env::var("DATABASE_URL")?).await?);
    app.at("/quiz/").get(WebSocket::new(get_quiz));
    app.listen("127.0.0.1:3000").await?;
    Ok(())
}

async fn get_quiz(_req: Request<()>, mut stream: WebSocketConnection) -> tide::Result<()> {
    while let Some(Ok(Message::Text(input))) = stream.next().await {
        let output: String = input.chars().rev().collect();
        stream
            .send_string(format!("{} | {}", &input, &output))
            .await?;
    }

    Ok(())
}
```

running [websocat](https://github.com/vi/websocat) to test the endpoint
```
websocat ws://localhost:3000/quiz/
```

returns a `WebSocket protocol error` and the server returns
```
thread 'async-std/runtime' panicked at 'We have err'd egregiously! Could not unwrap refcounted SQLx connection for COMMIT; handler may be storing connection or request inappropiately?', /home/cn/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-sqlx-0.6.1/src/lib.rs:312:17
```

which clearly occurs in tide-sqlx https://github.com/eaze/tide-sqlx/blob/latest/src/lib.rs#L312

commenting out the `app.with(SQLxMiddleware...)`-line makes the websocket-endpoint behave as expected.
but, am i right in my intuition assuming that it's tide-websockets that makes it err somehow?
